# Generated by Django 4.0.6 on 2022-07-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttracker',
            name='client_meeting',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
