# Generated by Django 4.0.6 on 2022-07-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkiapp', '0002_alter_projecttracker_client_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttracker',
            name='project_id',
        ),
    ]
